version: "3.9"
services:
  mssql:
    restart: always
    container_name: mssql
    networks:
      - backplane
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql
    ports:
      - "1433:1433"

  nats:
    image: nats:latest
    container_name: nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--user"
      - "${NATS_USER}"
      - "--pass"
      - "${NATS_PASSWORD}"
      - "--cluster_name"
      - "FcsEventCluster"
      - "--cluster"
      - "nats://0.0.0.0:6222"
    networks:
      - backplane

volumes:
  sqlserver_data:

networks:
  backplane:
    name: backplane